# -*- coding: utf-8 -*-
"""Custom Errors, Day 38

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Izh6cg2nZzK2EBwy5mInp3NZrshJT0-k
"""

a = int(input("Enter any value between 5 and 9"))
if(a<5 or a>9):
    raise ValueError("Value should be between 5 and 9")
    #Python error classes (search and study)

a = input("Enter your input here")
if(a=="quit"):
  print("Acknowledged")
else:
    raise ValueError("Error")